name: Deploy Node.js to EC2[node-express-js]

on:
  push:
    branches:
      - node-express-js

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Project (Optional)
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/app
            git pull origin main  # Make sure your EC2 instance has access to your repo
            npm install
            npm run build  # If needed
            pm2 restart all || pm2 start server.js --name "node-app"

