name: Build and Test[node-ts-lambda]

on:
  push:
    branches:
      - node-ts-lambda
  pull_request:
    branches:
      - node-ts-lambda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Build
        run: npm run build
